name: motskin
channels:
  - anaconda
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python==3.11.6
  - cuda==12.5.1
  - cudnn
  - pip==23.3
  - pip:
    - torch==2.1.1
    - torchvision==0.16.1
    - numpy==1.26.2
    - matplotlib==3.7.0
    - Pillow==10.4.0
    - pandas==2.1.3
    - termcolor==2.4.0
    - opencv-python==4.7.0.72
    - tqdm==4.65.0

